### ISSUE TITLE
need quic-go upgrade to compile against go1.20

### ISSUE THREAD

**Issue by chenrui333** [ginuerzh/gost#926]
👋 needs to update quic-go so that it can compile against go1.20, otherwise it would have the following error:
```
# github.com/lucas-clemente/quic-go/internal/qtls
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/lucas-clemente/quic-go@v0.28.1/internal/qtls/go120.go:6:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration
```

**Comment by ginuerzh** [comment]
Done!

**Comment by lasse717** [comment]
@here, I am still getting this error.
`cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration`
